### ISSUE TITLE
Npm can't remove package: react-router-guard-dirty-state: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by Englund0110** [WARP-LAB/react-router-guard-dirty-state#2]
When running NPM install, i am getting this error: 

```
25 verbose stack Error: \React\node_modules\react-router-guard-dirty-state: Appears to be a git repo or submodule.
25 verbose stack     at \AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:137:15
25 verbose stack     at \AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
25 verbose stack     at FSReqWrap.oncomplete (fs.js:166:5)
26 verbose cwd \React
27 verbose Windows_NT 10.0.15063
28 verbose argv "C:\\Program Files\\nodejs\\node.exe" "\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
29 verbose node v10.1.0
30 verbose npm  v6.3.0
31 error path \React\node_modules\react-router-guard-dirty-state
32 error code EISGIT
33 error git \React\node_modules\react-router-guard-dirty-state: Appears to be a git repo or submodule.
34 error git \React\node_modules\react-router-guard-dirty-state
35 error git Refusing to remove it. Update manually,
35 error git or move it out of the way first.
```

It seems that it cant be removed from node_modules.

**Comment by Englund0110** [comment]
Could you, @kroko  please remove the .git repository from the package?

**Comment by Englund0110** [comment]
@glennflanagan

**Comment by glennflanagan** [comment]
I don't have access to the NPM package so I can't do this. But there is a workaround here https://github.com/APSL/react-native-version-number/issues/13#issuecomment-341059894

@kroko it looks like you need to remove the .git folder from the npm package when you release.

**Comment by Englund0110** [comment]
Thanks for the answer. 

I will just use the 0.4 version, and hopefully it will be removed in the future.

**Comment by kroko** [comment]
`.git` removed, 0.0.6 pushed.
